//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_BanHoaEntities2 : DbContext
    {
        public QL_BanHoaEntities2()
            : base("name=QL_BanHoaEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BinhLuan> BinhLuan { get; set; }
        public DbSet<tblChiTietHoaDon> tblChiTietHoaDon { get; set; }
        public DbSet<tblDanhMucHoa> tblDanhMucHoa { get; set; }
        public DbSet<tblHinhAnh> tblHinhAnh { get; set; }
        public DbSet<tblHoa> tblHoa { get; set; }
        public DbSet<tblHoaDon> tblHoaDon { get; set; }
        public DbSet<tblKhachHang> tblKhachHang { get; set; }
        public DbSet<tblLoaiHoaChinh> tblLoaiHoaChinh { get; set; }
        public DbSet<tblNhanVien> tblNhanVien { get; set; }
        public DbSet<tblTinhTrang> tblTinhTrang { get; set; }
        public DbSet<tblVaiTro> tblVaiTro { get; set; }
    }
}
