//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietHoaDon
    {
        public int MaHD { get; set; }
        public int MaHoa { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
    
        public virtual tblHoa tblHoa { get; set; }
        public virtual tblHoaDon tblHoaDon { get; set; }
    }
}
