//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoa
    {
        public tblHoa()
        {
            this.BinhLuan = new HashSet<BinhLuan>();
            this.tblChiTietHoaDon = new HashSet<tblChiTietHoaDon>();
            this.tblHinhAnh = new HashSet<tblHinhAnh>();
        }
    
        public int MaHoa { get; set; }
        public string TenHoa { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public string MoTa { get; set; }
        public string AnhDaiDien { get; set; }
        public string DonViTinh { get; set; }
        public string MauSacChuDao { get; set; }
        public Nullable<int> MaDM { get; set; }
        public Nullable<int> MaLoaiChinh { get; set; }
    
        public virtual ICollection<BinhLuan> BinhLuan { get; set; }
        public virtual ICollection<tblChiTietHoaDon> tblChiTietHoaDon { get; set; }
        public virtual tblDanhMucHoa tblDanhMucHoa { get; set; }
        public virtual ICollection<tblHinhAnh> tblHinhAnh { get; set; }
        public virtual tblLoaiHoaChinh tblLoaiHoaChinh { get; set; }
    }
}
