//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoaiHoaChinh
    {
        public tblLoaiHoaChinh()
        {
            this.tblHoa = new HashSet<tblHoa>();
        }
    
        public int MaLoaiChinh { get; set; }
        public string TenLoaiChinh { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<tblHoa> tblHoa { get; set; }
    }
}
